name: hnapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  url_launcher: ^5.4.10
  built_collection: ^4.3.2
  built_value: ^7.1.0
  http: ^0.12.1
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.8.1
  webview_flutter: ^0.3.22+1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.7+3




  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner:  ^1.10.0
  built_value_generator: ^7.1.0

  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  fonts:
    - family: PressStart
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf
        - asset: fonts/EBGaramond-Italic-VariableFont_wght.ttf
        - asset: fonts/EBGaramond-VariableFont_wght.ttf
        - asset: fonts/Garamond Regular.ttf
        - asset: fonts/Garamond.ttf

